### ISSUE TITLE
Things that are impossible.

### ISSUE THREAD

**Issue by BronyfromOz** [WTFGeeks/Natural-Magic#85]
Crafting of heart canisters - Necrotic bones and necrotic skeletons appear to be non-existent.
Solo adventuring into the Nether - The sheer number of Lycanites that swarm you is stupid.  (Not to mention the ID Software lawsuits waiting to happen).
Playing for more than an hour without NEI dying the slow death.
Having your fill of Lycanites food -  Just keep stuffing 'til your saturation is maxed and then some. (Yes, I do have a problem with Lycanites)
Mining of Nether Quartz - None to be found.
Finding enough Lapis in the overworld -  Twilight Forest caves seem to be the only place for good amounts.

And an honorable mention to Ghast hunting.  So few I actually miss hearing the strange crying sounds.

P.S. Bravo for adding Lycanites and Vein Miner so that every good vein spawns a Geonach. You should get a Golden Troll award.

**Comment by TheMudpit** [comment]
You sound frustrated! I love the modpack, more for its potential than it's realisation but it is still a work in progress.  I have to have cheat mode enabled to overcome various problems such as the ones you mention. Eg. I never found any lapis in the overworld - not one single piece, so I agree with you on that one.  Additionally, my trips to the twighlight forest, to get lapis for my tinkers tools were plagued by weeping angels, constantly teleporting me, to places which were not loaded, and sometimes didn't load, leaving me stuck in a void. Fighting bosses was similarly interrupted by weeping angels. So  I have just updated to 0.7.1, and will be starting a new world.  The Lycanites problem has apparently been fixed in this patch.  I am grateful for the modpack nonetheless.  Particularly as it has the best magic mods, airships and sorting pipes - just a little tech to ease the pain of tedious inventory management - it's a perfect balance I think.  It will be great when the bugs get ironed out.

**Comment by BronyfromOz** [comment]
Yeah you're right.
I disabled Lycanites, Weeping Angels and Slime Carnage in my client, started a new game and I'm having a lot of fun.

**Comment by ArcticHowler** [comment]
I should consider doing the same... the items from Lycanite are op against normal mobs, but even they are useless against the Lycanite mobs because they're so numerous and deadly... not to mention trying to get out of the Twilight Forest with an army of weeping angels teleporting you across the world >.< Slime carnage though I found to be somewhat enjoyable... like the ninja turtles sewer that it has :D but yeah, NEI is having issues, unsure of source, would love to see it fixed... all in all, Lycanite needs to go, weeping angels at least need a number decrease if it remains...

**Comment by WTFGeeks** [comment]
Lycanites has had a big overhaul in the coming version, this was actually added in 0.7.1 but there was a known issue with lycanites resetting the config folder after a reinstall so you were not getting the configs I added but instead a fresh bath of configs this has been resolved though so I question if you are using the old config files. Lycanites is not being used in Natural Magic to add loads of dangerous mobs you'll find in 0.7.2 most are disabled entirely leaving mostly the passive mobs  to add a bit more intrigue to world exploration.  As far as weeping angels that is removed in 0.7.2 I cannot control there spawning in the twilight and the dungeons they created were causing a massive amount of lag when near them. I have also upped the vanilla mob spawning in the nether. Quartz has already been fixed check the closed issues :P lapiz is spawning in the overworld currently but is not set to the same height values as redstone hence why your used to seeing the ore everywhere while lapiz is spawning normally, I will add this to the increased ore weights in 0.7.2. NEI issues are due to waila and are a well known issue on both sides, the only known solution currently is to remove WAILA entirely, I'll let you decide if you want to do that.

**Comment by ArcticHowler** [comment]
So I was playing around and I can say that WAILA isn't the only culprit, also disabling it removes it from the list entirely as if it were fully removed instead of just disabled... but NEI without WAILA  refuses to use it's built in search function that should be at least 90% separate from WAILA, the delay on somethings related to NEI are still present with WAILA disabled. Might want to consider more of the mods conflicting with it(I've seen way more items in modpacks delay less often than this pack so I know it's not from NEI being overloaded...)

**Comment by BronyfromOz** [comment]
Only with this pack I've ever seen the NEI slowdown issue.

**Comment by WTFGeeks** [comment]
Alright so I'v spent a good morning looking into the hooking processes currently affecting nei, and I believe the culprit is ThaumicNEI if you want to try disabling this and let me know if that improves it, that would be great.

**Comment by ArcticHowler** [comment]
I didn't notice any slow down in the 7.2 version upon updating, left lycanite mobs on and still no issues, NEI was working, I didn't build anything however and there might be a probable issue with certain blocks so someone would need to test that to be certain, I'm not sure what all was changed in this version without a proper change log of sorts to be sure, but I will say that Slime Carnage is spawning too many sewers(almost 2 every 1-2 chunks in one direction, also had 2 slime labs next to each other, roughly 50 blocks apart, figured I'd mention it and a few other things while mentioning this.), and while I did find a summon minion weapon from lycanite, it never spawned in the minion(Rambora axeblade or w.e it was called, spawns those flying serpents that spit poison) I did however come across a stretch of land that didn't spawn in, hit a hobgoblin near it and it walked into it as if nothing was wrong, but came out invincible and aggressive, probably just a glitch in world gen or just needed to reload the chunk, but yeah... deleted the world as I only made it to test NEI and such, but yeah, overall working, don't know what you did, but no issues on my end beyond what was stated above... as such I didn't try disabling ThaumicNEI or anything else.

**Comment by BronyfromOz** [comment]
NEI working at 100% speed with zero lag without Thaumic NEI in 7.1.
Updating to 7.2 now.
edit - Zero lag in 7.2
